version: "3.9"
services:
  firebase:
    image: bandlabtechnologies/firebase-tools:9.18.0
    container_name: server-firebase-emulator
    environment:
      - GCP_PROJECT=project-test
      - FIRESTORE_PORT=8082
      - PUBSUB_PROJECT_ID=project-test
    ports:
      - 4000:4000 # emulator suite ui
      - 8082:8082 # firestore

  web:
    build:
      context: ./../
      dockerfile: dockerfiles/Dockerfile
    ports:
      - "5000:5000"
    command: sh -c "PYTHONDONTWRITEBYTECODE=1 FIRESTORE_EMULATOR_HOST=localhost:8082 GOOGLE_APPLICATION_CREDENTIALS=./fake_creds.json python3 /app/main.py"
    depends_on:
      - firebase
